[package]
name = "cpal-demo"
version = "0.1.0"
authors = ["Kawaki-san <rtkayy123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"